import type { Jurisdiction } from '@/types';

/**
 * Watch-source registry — the official pages and feeds the collector monitors.
 *
 * Sources verified 2026-07-20 against the collector's own retrieval pipeline
 * (targeted dry runs). `rss` sources are parsed as RSS/Atom feeds;
 * `html-index` sources are scraped for announcement links; `document`
 * sources are watched for content-hash changes. Hosts that reject plain
 * HTTP clients (GovCMS behind Akamai, APH, AWS WAF fronted state sites)
 * are marked fetchStrategy 'browser' and retrieved through the headless
 * browser; every other source still falls back to the browser when the
 * plain retriever fails. The collector tolerates per-source failures and
 * reports them in meta.json.
 */

export type SourceKind = 'html-index' | 'rss' | 'document';
export type SourceCategory = 'government' | 'regulator' | 'court';
export type SourceAutomation = 'automatic' | 'manual';
export type SourceFetchStrategy = 'http' | 'browser';

export interface WatchSource {
  id: string;
  name: string;
  jurisdiction: Jurisdiction;
  category: SourceCategory;
  url: string;
  kind: SourceKind;
  schedule: 'daily' | 'weekly';
  enabled: boolean;
  automation: SourceAutomation;
  /**
   * 'browser' skips the plain HTTP client and retrieves through the headless
   * browser directly — for hosts known to reject non-browser clients. The
   * default 'http' path still falls back to the browser on failure.
   */
  fetchStrategy?: SourceFetchStrategy;
  critical?: boolean;
  notes?: string;
}

export const WATCH_SOURCES: WatchSource[] = [
  // --- Federal: policy owners ---
  {
    id: 'pm-media',
    name: 'Prime Minister of Australia — media',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.pm.gov.au/media',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    critical: true,
    notes:
      'Whole-of-government announcements, including cross-portfolio AI policy decisions.',
  },
  {
    id: 'pmc-office-ai',
    name: 'Department of the Prime Minister and Cabinet — Office of AI',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.pmc.gov.au/domestic-policy/office-ai',
    kind: 'document',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    critical: true,
    notes:
      'Directly tracks the Office of AI mandate and national standards implementation; PMC serves an empty shell to plain HTTP clients, so the page is rendered in the headless browser.',
  },
  {
    id: 'industry-ai-publications',
    name: 'Department of Industry — AI publications',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.industry.gov.au/publications?pub-topic=2963',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    critical: true,
    notes:
      'AI-topic filtered publications index (Drupal views table) for formal policy, standards, frameworks and agreements; GovCMS rejects plain HTTP clients.',
  },
  {
    id: 'industry-ministers-media',
    name: 'Industry, Science and Resources ministers — media centre',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.minister.industry.gov.au/feed/all/all/rss.xml',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    critical: true,
    notes:
      'Official all-ministers RSS feed covering AI announcements, international agreements and infrastructure commitments; GovCMS rejects plain HTTP clients.',
  },
  {
    id: 'dta-media',
    name: 'Digital Transformation Agency — media releases',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.dta.gov.au/news-and-blogs/latest/feed/news_item',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    critical: true,
    notes:
      'Official DTA news RSS feed; GovCMS/Akamai rejects plain HTTP clients.',
  },
  {
    id: 'digital-gov-ai',
    name: 'digital.gov.au — AI in government policy hub',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.digital.gov.au/policy/ai',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    critical: true,
    notes: 'GovCMS/Akamai rejects plain HTTP clients.',
  },
  {
    id: 'disr-news',
    name: 'Department of Industry, Science and Resources — news',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.industry.gov.au/news',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Departmental news and media-release index; GovCMS rejects plain HTTP clients.',
  },
  {
    id: 'naic-news',
    name: 'National AI Centre — news and insights',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.ai.gov.au/news-and-insights',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'The page is now a curated hub rather than a dated index, so it is watched for content changes; GovCMS/Akamai rejects plain HTTP clients.',
  },
  {
    id: 'finance-news',
    name: 'Department of Finance — news (APS AI Plan, GovAI)',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.finance.gov.au/about-us/news',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'GovCMS/Akamai rejects plain HTTP clients.',
  },
  {
    id: 'agd-news',
    name: "Attorney-General's Department — news (copyright & AI)",
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.ag.gov.au/about-us/news-and-media',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: false,
    automation: 'manual',
    notes:
      'The departmental news index now returns 404 and no successor page is published (verified 2026-07-20); portfolio announcements are covered by agd-ministers-media.',
  },
  {
    id: 'agd-ministers-media',
    name: "Attorney-General's portfolio ministers — media centre",
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://ministers.ag.gov.au/media-centre',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Whole-of-government AI safety, privacy, copyright and automated-decision announcements; the host rejects plain HTTP clients.',
  },
  {
    id: 'treasury-publications',
    name: 'Treasury — publications (digital competition, consumer law)',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://treasury.gov.au/publication',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'Digital competition and consumer-law publications; the index markup exposes no extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'csiro-news',
    name: 'CSIRO — news (Data61, AI research)',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.csiro.au/en/news',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
  },
  {
    id: 'cyber-news',
    name: 'Australian Cyber Security Centre — news',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.cyber.gov.au/about-us/view-all-content/news',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'ASD/ACSC news index covering AI cyber guidance and joint statements; the host rejects plain HTTP clients.',
  },
  {
    id: 'apsc-latest-news',
    name: 'Australian Public Service Commission — latest news',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.apsc.gov.au/latest-news',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'APS-wide AI workforce, recruitment, capability and governance guidance; the host rejects plain HTTP clients.',
  },
  {
    id: 'anao-performance-audits',
    name: 'Australian National Audit Office — performance audit reports',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.anao.gov.au/pubs/performance-audit?items_per_page=120&page=0',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Commonwealth governance audits, including agency use and oversight of AI; the host rejects plain HTTP clients.',
  },
  {
    id: 'senate-ai-data-centres',
    name: 'Senate inquiry — artificial intelligence and data centres',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.aph.gov.au/Parliamentary_Business/Committees/Senate/Environment_and_Communications/AIdatacentres48P',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Tracks inquiry milestones, submissions and the report due in November 2026; APH returns 403 to plain HTTP clients.',
  },
  {
    id: 'senate-new-inquiries',
    name: 'Australian Senate — new committee inquiries',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.aph.gov.au/senate/rss/new_inquiries',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    notes:
      'Official Senate RSS feed for newly referred inquiries, including AI and data-centre scrutiny.',
  },
  {
    id: 'senate-reports',
    name: 'Australian Senate — committee reports tabled',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.aph.gov.au/senate/rss/reports',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    notes:
      'Official Senate RSS feed for committee reports and policy recommendations.',
  },
  {
    id: 'house-new-inquiries',
    name: 'House of Representatives — new committee inquiries',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.aph.gov.au/house/rss/house_inquiries',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Official House RSS feed for newly referred committee inquiries; APH returns 403 to plain HTTP clients. The feed is legitimately empty between referrals.',
  },
  {
    id: 'joint-new-inquiries',
    name: 'Parliamentary joint committees — new inquiries',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.aph.gov.au/house/rss/joint_inquiries',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Official joint-committee RSS feed for newly referred inquiries; APH returns 403 to plain HTTP clients. The feed is legitimately empty between referrals.',
  },
  {
    id: 'aph-bills-digests',
    name: 'Parliamentary Library — bills digests',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://parlinfo.aph.gov.au/parlInfo/feeds/rss.w3p;adv=yes;orderBy=date-eFirst;page=0;query=Date%3AthisYear%20Dataset%3Abillsdgs;resCount=100',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Official ParlInfo feed of Parliamentary Library bills digests — the leading indicator for bills before parliament, including AI legislation; APH rejects plain HTTP clients.',
  },
  {
    id: 'legislation-whats-new',
    name: 'Federal Register of Legislation — what’s new',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://www.legislation.gov.au/whatsnew',
    kind: 'document',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Newly registered acts and legislative instruments; the register is a client-rendered application, so the rendered page is watched for content changes.',
  },
  {
    id: 'agd-consultations',
    name: "Attorney-General's Department — consultation hub",
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://consultations.ag.gov.au/',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Open consultations on copyright and AI, automated decision-making and privacy reform — policy signals months before announcements.',
  },
  {
    id: 'industry-consultations',
    name: 'Department of Industry — consultation hub',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://consult.industry.gov.au/',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Open DISR consultations, including AI regulatory proposals; the hub markup exposes no extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'treasury-consultations',
    name: 'Treasury — consultation hub',
    jurisdiction: 'federal',
    category: 'government',
    url: 'https://consult.treasury.gov.au/',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Open Treasury consultations, including digital competition and consumer-law reform; the hub markup exposes no extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'aemc-media',
    name: 'Australian Energy Market Commission — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.aemc.gov.au/news-centre/media-releases',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'Energy-market rules and standards affecting large AI and data-centre loads (Drupal views table).',
  },
  // --- Federal: regulators ---
  {
    id: 'oaic-media',
    name: 'OAIC — media centre',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.oaic.gov.au/news/media-centre',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    notes: 'The OAIC RSS feed omits item links, so scrape the index instead.',
  },
  {
    id: 'accc-rss',
    name: 'ACCC — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.accc.gov.au/rss/media_releases.xml',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
  },
  {
    id: 'apra-rss',
    name: 'APRA — news',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.apra.gov.au/rss.xml',
    kind: 'rss',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
  },
  {
    id: 'asic-newsroom',
    name: 'ASIC — newsroom',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://asic.gov.au/newsroom',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'The newsroom list is client-rendered, so it is retrieved through the headless browser.',
  },
  {
    id: 'acma-media',
    name: 'ACMA — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.acma.gov.au/media-releases',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Communications and media regulation, including misinformation, deepfakes and online platforms; GovCMS rejects plain HTTP clients.',
  },
  {
    id: 'tga-media',
    name: 'TGA — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.tga.gov.au/news/media-releases',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Therapeutic goods regulation, including AI as a medical device and software-as-medical-device guidance; GovCMS rejects plain HTTP clients.',
  },
  {
    id: 'ipa-news',
    name: 'IP Australia — news',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.ipaustralia.gov.au/about-us/news-and-community/news',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Intellectual property practice at the AI interface — AI-assisted inventions, examination practice and copyright signals.',
  },
  {
    id: 'fwc-news',
    name: 'Fair Work Commission — news and media',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.fwc.gov.au/about-us/news-and-media',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Workplace-relations decisions and guidance touching AI in hiring, monitoring and workplace change.',
  },
  {
    id: 'teqsa-news',
    name: 'TEQSA — latest news',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.teqsa.gov.au/latest-news',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Higher-education regulation including generative AI and academic integrity; the news index markup exposes no extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'aec-media',
    name: 'AEC — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.aec.gov.au/media/media-releases.htm',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Electoral communications and AI/deepfake guidance; the legacy index markup exposes no extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'esafety-media',
    name: 'eSafety Commissioner — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.esafety.gov.au/newsroom/media-releases',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'GovCMS/Akamai rejects plain HTTP clients.',
  },
  {
    id: 'pc-media',
    name: 'Productivity Commission — media releases',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://www.pc.gov.au/media-speeches/media-releases',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'Inquiry milestones including the digital-economy and AI stream; the redesigned site exposes no extractable index entries, so the page is watched for content changes.',
  },
  {
    id: 'ahrc-media',
    name: 'Australian Human Rights Commission — media centre',
    jurisdiction: 'federal',
    category: 'regulator',
    url: 'https://humanrights.gov.au/about-us/media-centre',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'The host rejects plain HTTP clients.',
  },
  // --- Courts ---
  {
    id: 'fedcourt-practice-notes',
    name: 'Federal Court — practice notes',
    jurisdiction: 'federal',
    category: 'court',
    url: 'https://www.fedcourt.gov.au/law-and-practice/practice-documents/practice-notes',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Practice notes including generative-AI usage directions; the directory markup exposes no extractable entries, so the page is watched for content changes. The host rejects plain HTTP clients.',
  },
  {
    id: 'nsw-sc-practice-notes',
    name: 'NSW Supreme Court — practice notes',
    jurisdiction: 'nsw',
    category: 'court',
    url: 'https://supremecourt.nsw.gov.au/practice-procedure/practice-notes0.html',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'Practice notes including the generative-AI practice note; the directory markup exposes no extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'vic-sc-practice-notes',
    name: 'Victorian Supreme Court — practice notes',
    jurisdiction: 'vic',
    category: 'court',
    url: 'https://www.supremecourt.vic.gov.au/areas/legal-resources/practice-notes',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
  },
  {
    id: 'qld-courts-news',
    name: 'Queensland Courts — news',
    jurisdiction: 'qld',
    category: 'court',
    url: 'https://www.courts.qld.gov.au/newsroom/news',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'Court announcements including AI practice directions; the news index markup exposes no extractable entries, so the page is watched for content changes.',
  },
  // --- States and territories ---
  {
    id: 'nsw-digital-ai',
    name: 'Digital NSW — artificial intelligence',
    jurisdiction: 'nsw',
    category: 'government',
    url: 'https://www.digital.nsw.gov.au/policy/artificial-intelligence',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'NSW AI policy and assurance framework hub; the page exposes no extractable index entries, so it is watched for content changes.',
  },
  {
    id: 'nsw-media-releases',
    name: 'NSW Government — media releases',
    jurisdiction: 'nsw',
    category: 'government',
    url: 'https://www.nsw.gov.au/media-releases',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Whole-of-government NSW announcements, including AI policy and digital government decisions.',
  },
  {
    id: 'vic-ai',
    name: 'vic.gov.au — generative AI guidance',
    jurisdiction: 'vic',
    category: 'government',
    url: 'https://www.vic.gov.au/administrative-guideline-safe-responsible-use-gen-ai-vps',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
  },
  {
    id: 'ovic-news',
    name: 'OVIC — news',
    jurisdiction: 'vic',
    category: 'regulator',
    url: 'https://ovic.vic.gov.au/about-us/news-and-media/news',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    notes:
      'Victorian information commissioner — the most active state privacy regulator on AI and automated decision-making.',
  },
  {
    id: 'qld-qgea-ai',
    name: 'Queensland QGEA — AI governance policy',
    jurisdiction: 'qld',
    category: 'government',
    url: 'https://www.forgov.qld.gov.au/information-technology/queensland-government-enterprise-architecture-qgea/qgea-directions-and-guidance/qgea-policies-standards-and-guidelines/artificial-intelligence-governance-policy',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'AWS WAF challenges plain HTTP clients.',
  },
  {
    id: 'qld-ministerial-statements',
    name: 'Queensland Government — ministerial media statements',
    jurisdiction: 'qld',
    category: 'government',
    url: 'https://statements.qld.gov.au/',
    kind: 'document',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Whole-of-government Queensland announcements; the statements list is client-rendered without extractable entries, so the page is watched for content changes.',
  },
  {
    id: 'wa-media-statements',
    name: 'WA Government — media statements',
    jurisdiction: 'wa',
    category: 'government',
    url: 'https://www.mediastatements.wa.gov.au/',
    kind: 'html-index',
    schedule: 'daily',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes:
      'Whole-of-government WA announcements, including AI policy and digital government decisions.',
  },
  {
    id: 'wa-ai-policy',
    name: 'WA — AI policy and assurance framework',
    jurisdiction: 'wa',
    category: 'government',
    url: 'https://www.wa.gov.au/government/publications/wa-government-artificial-intelligence-policy-and-assurance-framework',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'The host rejects plain HTTP clients.',
  },
  {
    id: 'sa-office-for-ai',
    name: 'SA Office for AI',
    jurisdiction: 'sa',
    category: 'government',
    url: 'https://www.ai.sa.gov.au/',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'manual',
    notes:
      'Returns 403 to every automated client, including the headless browser (verified 2026-07-20); review manually.',
  },
  {
    id: 'tas-dpac-policies',
    name: 'Tasmania DPAC — digital strategy policies',
    jurisdiction: 'tas',
    category: 'government',
    url: 'https://www.dpac.tas.gov.au/divisions/digital_strategy_and_services/policies',
    kind: 'html-index',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'The host rejects plain HTTP clients.',
  },
  {
    id: 'act-ai-policy',
    name: 'ACT Government — AI policy',
    jurisdiction: 'act',
    category: 'government',
    url: 'https://www.act.gov.au/open/act-government-artificial-intelligence-policy',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'The host rejects plain HTTP clients.',
  },
  {
    id: 'nt-ai-assurance',
    name: 'NT Digital Territory — AI assurance framework',
    jurisdiction: 'nt',
    category: 'government',
    url: 'https://digitalterritory.nt.gov.au/digital-government/strategies-and-guidance/policies-standards-and-guidance/artificial-intelligence-assurance-framework',
    kind: 'document',
    schedule: 'weekly',
    enabled: true,
    automation: 'automatic',
    fetchStrategy: 'browser',
    notes: 'Returns 403 to non-browser user agents.',
  },
];

export function getAutomaticSources(): WatchSource[] {
  return WATCH_SOURCES.filter(
    (source) => source.enabled && source.automation === 'automatic',
  );
}

/** @deprecated Prefer getAutomaticSources() so the coverage boundary is clear. */
export const getEnabledSources = getAutomaticSources;

export function getManualSources(): WatchSource[] {
  return WATCH_SOURCES.filter(
    (source) => source.enabled && source.automation === 'manual',
  );
}

export function getSourceById(id: string): WatchSource | undefined {
  return WATCH_SOURCES.find((source) => source.id === id);
}
